/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (number 62), U7[4]/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB17 (number 63), U10[1]/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTE0 (number 1), J15[P8]/SDHC0_D1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SDHC0_D1_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SDHC0_D1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDHC0_D1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE1 (number 2), J15[P7]/SDHC0_D0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SDHC0_D0_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SDHC0_D0_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDHC0_D0_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE2 (number 3), J15[P5]/SDHC0_DCLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SDHC0_DCLK_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SDHC0_DCLK_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDHC0_DCLK_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTE3 (number 4), J15[P3]/SDHC0_CMD
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SDHC0_CMD_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SDHC0_CMD_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDHC0_CMD_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTE4 (number 5), J15[P2]/SDHC0_D3
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SDHC0_D3_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SDHC0_D3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDHC0_D3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE5 (number 6), J15[P1]/SDHC0_D2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SDHC0_D2_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SDHC0_D2_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDHC0_D2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE6 (number 7), J15[G1]/SD_CARD_DETECT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SDHC_CD_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SDHC_CD_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SDHC_CD_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SDHC_CD_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDHC_CD_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name DAC0_OUT (number 27), J4[11]
  @{ */
/* @} */

/*! @name PORTE24 (number 31), J2[20]/U8[4]/I2C0_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ACCEL_SCL_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ACCEL_SCL_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ACCEL_SCL_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTE25 (number 32), J2[18]/U8[6]/I2C0_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ACCEL_SDA_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ACCEL_SDA_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ACCEL_SDA_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
